import { StatusBar, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  button: {
    backgroundColor: "black",
    width: "100%",
    padding: 15,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: "center",
  },
  buttonContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    backgroundColor: "white",
  },
  buttonOutline: {
    backgroundColor: "white",
    marginTop: 10,
    borderWidth: 2,
  },
  buttonOutlineText: {
    color: "black",
    fontWeight: "700",
    fontSize: 16,
  },
  buttonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
    textAlign: "center",
  },
  categoryButton: {
    backgroundColor: "white",
    padding: 15,
    borderRadius: 10,
    margin: 5,
    borderWidth: 2,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderTopWidth: 2,
  },
  chuckButton: {
    backgroundColor: "white",
    padding: 10,
    borderRadius: 10,
    margin: 5,
    borderWidth: 2,
  },
  deleteButton: {
    backgroundColor: "black",
    padding: 10,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: "center",
    width: "30%",
    margin: 5,
  },
  deleteButtonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
  },
  editButton: {
    padding: 10,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: "center",
    width: "30%",
    margin: 5,
  },
  editButtonText: {
    color: "black",
    fontWeight: "700",
    fontSize: 16,
  },
  error: {
    marginTop: 10,
    padding: 10,
    color: "#fff",
    backgroundColor: "#ff0000",
  },
  fetchContainer: {
    flex: 1,
    width: "80%",
    backgroundColor: "white",
  },
  homeContainer: {
    flex: 1,
    width: "80%",
    backgroundColor: "white",
  },
  input: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    marginTop: 10,
    borderWidth: 2,
    fontSize: 16,
    textAlignVertical: "top",
  },
  inputContainer: {
    flex: 1,
    width: "80%",
    backgroundColor: "white",
  },
  jokeButtonView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  jokeText: {
    color: "black",
    fontWeight: "700",
    fontSize: 16,
  },
  jokesContainer: {
    margin: 10,
    borderRadius: 20,
    borderWidth: 2,
    padding: 10,
    backgroundColor: "white",
  },
  modal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    marginTop: 20,
  },
  modalButton: {
    backgroundColor: "black",
    padding: 10,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: "center",
    width: "30%",
    margin: 5,
  },
  modalButtonView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  modalInput: {
    height: 170,
    width: "110%",
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    margin: 10,
    borderWidth: 2,
    fontWeight: "700",
    fontSize: 18,
    textAlignVertical: "top",
  },
  modalText: {
    textAlign: "center",
    fontSize: 30,
    fontWeight: "700",
  },
  shareButton: {
    backgroundColor: "black",
    width: "50%",
    padding: 5,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: "center",
  },
  scrollView: {
    flex: 0,
    paddingBottom: 100,
    alignItems: "center",
  },
  success: {
    marginTop: 10,
    padding: 10,
    color: "#fff",
    backgroundColor: "#009933",
  },
});
